### ISSUE TITLE
[DRC-266] [Bug] Failed to copy image to clipboard

### ISSUE THREAD

**Issue by i-dalbo** [DataRecce/recce#211] opened 2024-03-06 13:35 UTC
### Current Behavior

In the Checklist section, when I try to `Copy to Clipboard` a checklist item, I am returned with an error `ReferenceError: ClipboardItem is not defined` (see image). I am not sure if it is a system or configuration problem from my side, but I don't find docs to try to solve this.

![image](https://github.com/DataRecce/recce/assets/94531532/77500aa8-0f88-4d2f-8a48-fe8a94aa6465)

### Expected Behavior

I would expect the checklist item to be copied to the clipboard.

### Steps To Reproduce

1. clone this https://github.com/idalbo/dbt_jaffle_docker
2. if on windows, use WSL
3. navigate to the project root folder
4. run the make commands as indicated in the docs
5. run `recce server --host 0.0.0.0`
6. add a checklist item
7. try to copy to clipboard

### Environment

- recce: 0.7.0
- OS: Windows/WSL
- Python: 3.9
- Data Warehouse: postgres
- dbt: 1.7.9

<sub>[DRC-266](https://linear.app/piperider/issue/DRC-266/[bug]-failed-to-copy-image-to-clipboard)</sub>

**Comment by popcornylu** [comment] 2024-03-07 01:37
Hi @i-dalbo 

Thanks for your feedback. I can reproduce in chrome if the server served as http 
![image](https://github.com/DataRecce/recce/assets/860633/e5c190d5-9a26-46bf-886b-1692916269e4)

The reason is clipboard is forbidden in `http`. See [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard#using_the_clipboard_api)

A possible solution, 
1. Use `https` instead
2. Use `localhost` instead.
3. Manually screenshot provided by the OS. 


What recce can improve.
1. Show better error message to hint users about the permission issue.

**Comment by popcornylu** [comment] 2024-03-07 02:37
HI, @i-dalbo 

May i know more about your use case? If you use recce for  personal development/review use, just use `localhost` even you run it in the docker/container.

Or the container is hosted in the remote server and the server is shared with your collaborators?

**Comment by i-dalbo** [comment] 2024-03-07 07:41
hey @popcornylu thanks for your answer!

I use recce from the container in `localhost`. Sorry, I omitted the address, so it should technically work in my case since I am using `localhost`?  I forgot to mention this is from Firefox, haven't tried other browsers.

**Comment by popcornylu** [comment] 2024-03-08 02:46
Oh yes.. I can reproduce it at localhost. It should work. Let me see what went wrong. Thanks for the important information.

![image](https://github.com/DataRecce/recce/assets/860633/3327174a-0dca-4a6a-90a2-6c0a5db42d3b)

**Comment by popcornylu** [comment] 2024-03-08 02:58
This is a compatibility problem.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard#browser_compatibility

In firefox, we may need to fallback to the old `document.execCommand("copy")`

**Comment by popcornylu** [comment] 2024-03-18 00:01
Fixed in v0.9.0. In firefox, it would prompt a dialog to download the image.

**Closed by popcornylu** 2024-03-18 00:01 UTC
Labels: bug, linear, triage
